### ISSUE TITLE
Add "add person" button on day check-in page

### ISSUE THREAD

**Issue by Clam-** [Clam-/ConfApp#1]
ADD OPTION TO ADD NEW PERSON FROM DAY-REGISTRATION PAGE:
link goes to "newperson" page with prefilled boxes of "add to session" field!!
Don't forget.

**Comment by clammet** [comment]
I think I forgot :((

**Comment by clammet** [comment]
Finally done in d17f81a5ec5c878cb24ea1ba9ed3fe2eb973bc85
