### ISSUE TITLE
Sport sessions should be flagged on the session?

### ISSUE THREAD

**Issue by Clam-** [Clam-/ConfApp#5]
Instead of checking and marking them on the template?

**Comment by clammet** [comment]
Good idea, but not really sure about a good way to do this yet.

**Comment by clammet** [comment]
Additional modifications for this in e586c58dea352dad591b920a5f9fc95880cf6c22

**Comment by clammet** [comment]
Finished up with cf76eeab5a273adbf8106bace9e87ac19e532d4d
