### ISSUE TITLE
2019 - TODO

### ISSUE THREAD

**Issue by Clam-** [Clam-/ConfApp#9]
* ~~Fix table headers on other pages~~
* Test bootstrap native table striping/hover (although it never worked in bootstrap 3 for my purpose)
* ~~Handout list processing~~
* ~~Session Host processing~~
* ~~Clear other issues.~~

**Comment by clammet** [comment]
Session Host processing done in f035f1b92fa0904f2f07013d57c092b61d631e4f

**Comment by clammet** [comment]
Table headers done: 29c8021a5b0e42da3cdaac01b7ac337c5334e6da

**Comment by clammet** [comment]
Handout list processing done in a1b19cadace714647877f045af93a6d7f6fdf7a9

**Comment by clammet** [comment]
2019 Done I guess.
